module.exports = [
  // ── Wikipedia (broad topics) ──────────────────────────────────────────────
  'https://en.wikipedia.org/wiki/Main_Page',
  'https://en.wikipedia.org/wiki/Science',
  'https://en.wikipedia.org/wiki/Technology',
  'https://en.wikipedia.org/wiki/History',
  'https://en.wikipedia.org/wiki/Mathematics',
  'https://en.wikipedia.org/wiki/Physics',
  'https://en.wikipedia.org/wiki/Chemistry',
  'https://en.wikipedia.org/wiki/Biology',
  'https://en.wikipedia.org/wiki/Computer_science',
  'https://en.wikipedia.org/wiki/Artificial_intelligence',
  'https://en.wikipedia.org/wiki/Machine_learning',
  'https://en.wikipedia.org/wiki/Programming_language',
  'https://en.wikipedia.org/wiki/Internet',
  'https://en.wikipedia.org/wiki/World_Wide_Web',
  'https://en.wikipedia.org/wiki/Economics',
  'https://en.wikipedia.org/wiki/Philosophy',
  'https://en.wikipedia.org/wiki/Music',
  'https://en.wikipedia.org/wiki/Film',
  'https://en.wikipedia.org/wiki/Earth',
  'https://en.wikipedia.org/wiki/Universe',
  'https://en.wikipedia.org/wiki/United_States',
  'https://en.wikipedia.org/wiki/United_Kingdom',
  'https://en.wikipedia.org/wiki/Human',
  'https://en.wikipedia.org/wiki/Evolution',
  'https://en.wikipedia.org/wiki/Climate_change',
  'https://en.wikipedia.org/wiki/Space_exploration',
  'https://en.wikipedia.org/wiki/Quantum_mechanics',
  'https://en.wikipedia.org/wiki/Relativity',
  'https://en.wikipedia.org/wiki/DNA',
  'https://en.wikipedia.org/wiki/Cryptocurrency',
  'https://en.wikipedia.org/wiki/Blockchain',
  'https://en.wikipedia.org/wiki/Electric_vehicle',
  'https://en.wikipedia.org/wiki/Solar_energy',
  'https://en.wikipedia.org/wiki/Nuclear_power',
  'https://en.wikipedia.org/wiki/Vaccine',
  'https://en.wikipedia.org/wiki/Psychology',
  'https://en.wikipedia.org/wiki/Sociology',
  'https://en.wikipedia.org/wiki/Architecture',
  'https://en.wikipedia.org/wiki/Literature',
  'https://en.wikipedia.org/wiki/Sports',
  'https://en.wikipedia.org/wiki/Football',
  'https://en.wikipedia.org/wiki/Basketball',
  'https://en.wikipedia.org/wiki/Olympic_Games',
  'https://en.wikipedia.org/wiki/Food',
  'https://en.wikipedia.org/wiki/Nutrition',
  'https://en.wikipedia.org/wiki/Medicine',
  'https://en.wikipedia.org/wiki/Surgery',
  'https://en.wikipedia.org/wiki/Mental_health',
  'https://en.wikipedia.org/wiki/Democracy',
  'https://en.wikipedia.org/wiki/Capitalism',
  'https://en.wikipedia.org/wiki/Socialism',

  // ── Tech news ─────────────────────────────────────────────────────────────
  'https://news.ycombinator.com',
  'https://news.ycombinator.com/news?p=2',
  'https://arstechnica.com',
  'https://www.theverge.com',
  'https://techcrunch.com',
  'https://www.wired.com',
  'https://www.technologyreview.com',
  'https://venturebeat.com',
  'https://www.zdnet.com',
  'https://www.engadget.com',

  // ── General news ──────────────────────────────────────────────────────────
  'https://www.bbc.com/news',
  'https://www.reuters.com',
  'https://apnews.com',
  'https://www.npr.org/sections/news',

  // ── Programming & dev docs ────────────────────────────────────────────────
  'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  'https://developer.mozilla.org/en-US/docs/Web/HTML',
  'https://developer.mozilla.org/en-US/docs/Web/CSS',
  'https://developer.mozilla.org/en-US/docs/Web/API',
  'https://developer.mozilla.org/en-US/docs/Learn',
  'https://nodejs.org/en/docs',
  'https://docs.python.org/3/tutorial/',
  'https://docs.python.org/3/library/',
  'https://devdocs.io',
  'https://www.w3schools.com/js/',
  'https://www.w3schools.com/html/',
  'https://www.w3schools.com/css/',
  'https://www.w3schools.com/python/',
  'https://stackoverflow.com/questions?sort=votes&pagesize=50',
  'https://stackoverflow.com/questions?sort=newest',
  'https://github.com/trending',
  'https://github.com/trending/javascript',
  'https://github.com/trending/python',
  'https://github.com/trending/typescript',

  // ── Languages & frameworks ────────────────────────────────────────────────
  'https://www.rust-lang.org',
  'https://go.dev/doc/',
  'https://www.python.org/about/',
  'https://www.typescriptlang.org/docs/',
  'https://reactjs.org/docs/getting-started.html',
  'https://vuejs.org/guide/introduction.html',
  'https://svelte.dev/docs',
  'https://nextjs.org/docs',
  'https://deno.com',

  // ── Science ───────────────────────────────────────────────────────────────
  'https://www.nasa.gov',
  'https://www.nasa.gov/news',
  'https://www.nationalgeographic.com/science',
  'https://www.scientificamerican.com',
  'https://phys.org',
  'https://www.nature.com/news',
  'https://www.newscientist.com',
  'https://arxiv.org/list/cs.AI/recent',
  'https://arxiv.org/list/cs.LG/recent',

  // ── Learning ──────────────────────────────────────────────────────────────
  'https://www.khanacademy.org',
  'https://ocw.mit.edu',
  'https://www.coursera.org',
  'https://www.edx.org',

  // ── Reference ─────────────────────────────────────────────────────────────
  'https://www.britannica.com',
  'https://www.merriam-webster.com',
  'https://www.gutenberg.org',
  'https://archive.org/search',
  'https://howstuffworks.com',
  'https://xkcd.com/archive',
  'https://www.imdb.com/chart/top',
  'https://www.imdb.com/chart/toptv',
];
